### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ghost** [niklasb/elgoog#1]
hello, I'm sorry I'm not good at English...

when I run you exp, it not work. and I find it

![image](https://user-images.githubusercontent.com/34005655/47269078-be9e0e80-d58b-11e8-9c91-9d84585fe23d.png)
unicode where not work...

and I change it to...
![image](https://user-images.githubusercontent.com/34005655/47269084-e2615480-d58b-11e8-981f-68c58dd8d97d.png)

I think may be you are wrong.... I;m sorry, I'm not good at English... So may be my word is impolite.

**Comment by niklasb** [comment]
Maybe it has to do with your locale or other differences in settings
